-- 목 게시글 300개 생성 (일부는 임시저장)

INSERT INTO board (user_id, author, nickname, title, content, status, view_count, like_count, comment_count, is_draft, is_pinned, is_important, created_at, updated_at) VALUES
-- Spring/Java 관련 게시글 (1-50)
(2, '김철수', '코딩마스터', 'Spring Boot 3.0 새로운 기능 정리 #Spring #Java', 'Spring Boot 3.0에서 추가된 새로운 기능들을 정리해봤습니다. #Spring #Java #SpringBoot', 'PUBLIC', 145, 23, 0, false, false, false, NOW() - INTERVAL '30 days', NOW() - INTERVAL '30 days'),
(3, '이영희', '개발왕초보', 'JPA N+1 문제 해결 방법 #JPA #최적화', 'JPA 사용 시 자주 발생하는 N+1 문제를 해결하는 여러 방법을 공유합니다. #JPA #최적화 #Spring', 'PUBLIC', 289, 45, 0, false, false, false, NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
(4, '박민수', 'JavaLover', 'Java 17 vs Java 21 무엇을 써야할까? #Java', 'Java 17과 Java 21의 차이점과 선택 기준을 정리했습니다. #Java #버전선택', 'PUBLIC', 178, 31, 0, false, false, false, NOW() - INTERVAL '27 days', NOW() - INTERVAL '27 days'),
(5, '정다은', 'DB전문가', 'RestTemplate vs WebClient 비교 #Spring', 'Spring에서 HTTP 통신을 위한 두 가지 방법을 비교 분석합니다. #Spring #HTTP #비동기', 'PUBLIC', 203, 38, 0, false, false, false, NOW() - INTERVAL '26 days', NOW() - INTERVAL '26 days'),
(6, '강호준', '프론트엔드러', 'Spring Security JWT 인증 구현 #보안', 'JWT를 활용한 Spring Security 인증 구현 가이드입니다. #보안 #JWT #Spring', 'PUBLIC', 412, 67, 0, false, false, false, NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
(7, '윤서연', '백엔드개발자', 'MyBatis vs JPA 어떤 것을 선택할까? #DB', 'MyBatis와 JPA의 장단점을 비교하고 선택 기준을 제시합니다. #DB #ORM #JPA', 'PUBLIC', 256, 42, 0, false, false, false, NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
(8, '임태희', '풀스택지망생', 'Spring Batch 대용량 처리 최적화 #배치', '대용량 데이터 배치 처리를 최적화하는 방법을 공유합니다. #배치 #최적화 #Spring', 'PUBLIC', 189, 29, 0, false, false, false, NOW() - INTERVAL '23 days', NOW() - INTERVAL '23 days'),
(9, '오하늘', '알고리즘킬러', 'Lombok 사용 시 주의사항 #Java', 'Lombok 어노테이션 사용 시 주의해야 할 점들을 정리했습니다. #Java #Lombok #코딩', 'PUBLIC', 167, 25, 0, false, false, false, NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
(10, '서준호', '데이터분석가', 'Spring AOP 실전 활용법 #Spring', 'AOP를 실제 프로젝트에서 활용하는 다양한 방법을 소개합니다. #Spring #AOP #디자인패턴', 'PUBLIC', 234, 41, 0, false, false, false, NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
(11, '한지우', 'AI연구원', 'Hibernate 성능 튜닝 가이드 #최적화', 'Hibernate 쿼리 성능을 향상시키는 실전 팁을 공유합니다. #최적화 #Hibernate #JPA', 'PUBLIC', 198, 33, 0, false, false, false, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),

-- React/Frontend 관련 (51-100)
(18, '류준서', 'React개발자', 'React 18 신기능 정리 #React', 'React 18에서 추가된 Concurrent Features를 정리했습니다. #React #프론트엔드', 'PUBLIC', 276, 48, 0, false, false, false, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(19, '문서윤', 'Vue마스터', 'useState vs useReducer 언제 사용할까? #React', 'React Hook 선택 가이드입니다. #React #Hook #상태관리', 'PUBLIC', 189, 34, 0, false, false, false, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(20, '진도현', 'Angular전문가', 'Next.js SSR vs CSR 성능 비교 #Next', 'Next.js의 렌더링 방식별 성능을 비교 분석했습니다. #Next #React #성능', 'PUBLIC', 312, 56, 0, false, false, false, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
(21, '남주아', 'Node.js개발자', 'TypeScript 타입 추론 완벽 가이드 #TypeScript', 'TypeScript의 강력한 타입 추론 기능을 마스터하세요. #TypeScript #JavaScript', 'PUBLIC', 245, 43, 0, false, false, false, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(22, '표지훈', 'Python마스터', 'Recoil vs Redux 상태관리 비교 #상태관리', 'React 상태관리 라이브러리 비교 분석입니다. #상태관리 #React #Redux', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),

-- 데이터베이스 관련 (101-150)
(5, '정다은', 'DB전문가', 'PostgreSQL vs MySQL 성능 비교 #DB', '두 데이터베이스의 성능을 실측 데이터로 비교했습니다. #DB #PostgreSQL #MySQL', 'PUBLIC', 367, 62, 0, false, false, false, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
(12, '권수아', '클라우드엔지니어', 'MongoDB 인덱스 최적화 전략 #NoSQL', 'MongoDB에서 쿼리 성능을 극대화하는 인덱스 전략입니다. #NoSQL #MongoDB #최적화', 'PUBLIC', 198, 35, 0, false, false, false, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(13, '송민재', 'DevOps전문가', 'Redis 캐시 전략 정리 #캐시', 'Redis를 활용한 다양한 캐싱 전략을 소개합니다. #캐시 #Redis #성능', 'PUBLIC', 423, 71, 0, false, false, false, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(14, '조예린', '보안전문가', 'SQL 쿼리 최적화 실전 팁 #최적화', '실무에서 바로 적용 가능한 SQL 최적화 기법들입니다. #최적화 #SQL #DB', 'PUBLIC', 334, 58, 0, false, false, false, NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),
(15, '배현우', '모바일개발자', 'ElasticSearch 검색 엔진 구축기 #검색', 'ElasticSearch로 강력한 검색 기능을 구현한 경험을 공유합니다. #검색 #ElasticSearch', 'PUBLIC', 256, 44, 0, false, false, false, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),

-- DevOps/인프라 (151-200)
(13, '송민재', 'DevOps전문가', 'Docker 컨테이너 최적화 #Docker', 'Docker 이미지 크기를 줄이고 성능을 높이는 방법입니다. #Docker #컨테이너 #최적화', 'PUBLIC', 289, 49, 0, false, false, false, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(34, '피우진', 'Docker마스터', 'Kubernetes 입문 가이드 #K8s', 'Kubernetes 기본 개념과 실습 가이드입니다. #K8s #컨테이너 #오케스트레이션', 'PUBLIC', 412, 68, 0, false, false, false, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
(35, '함수빈', 'K8s전문가', 'AWS Lambda 서버리스 아키텍처 #AWS', '서버리스로 비용을 절감한 사례를 공유합니다. #AWS #서버리스 #Lambda', 'PUBLIC', 345, 59, 0, false, false, false, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(36, '곽하율', 'AWS전문가', 'CI/CD 파이프라인 구축 완벽 가이드 #CICD', 'Jenkins, GitHub Actions를 활용한 CI/CD 구축 경험입니다. #CICD #DevOps', 'PUBLIC', 378, 64, 0, false, false, false, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(39, '민재원', 'CI/CD마스터', 'Nginx 성능 튜닝 실전 #Nginx', 'Nginx 설정 최적화로 트래픽을 2배 감당한 경험입니다. #Nginx #성능 #최적화', 'PUBLIC', 298, 52, 0, false, false, false, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),

-- 알고리즘/자료구조 (201-220)
(9, '오하늘', '알고리즘킬러', '이진 탐색 트리 구현 완벽 가이드 #알고리즘', 'BST를 처음부터 끝까지 구현하며 배우는 가이드입니다. #알고리즘 #자료구조', 'PUBLIC', 267, 46, 0, false, false, false, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(9, '오하늘', '알고리즘킬러', '동적 프로그래밍 패턴 정리 #알고리즘', 'DP 문제 유형별 접근 방법을 정리했습니다. #알고리즘 #DP #코딩테스트', 'PUBLIC', 389, 66, 0, false, false, false, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(10, '서준호', '데이터분석가', 'LeetCode Top 100 문제 풀이 #코딩테스트', 'LeetCode 인기 문제 풀이와 해설입니다. #코딩테스트 #알고리즘', 'PUBLIC', 456, 78, 0, false, false, false, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
(22, '표지훈', 'Python마스터', '그래프 알고리즘 완전 정복 #알고리즘', 'DFS, BFS부터 다익스트라까지 그래프 알고리즘 총정리입니다. #알고리즘 #그래프', 'PUBLIC', 334, 57, 0, false, false, false, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),

-- 취업/이직 (221-240)
(44, '예민성', 'PM지망생', '신입 개발자 면접 후기 #취업', '대기업 SI 신입 개발자 면접 경험을 공유합니다. #취업 #면접 #신입', 'PUBLIC', 589, 94, 0, false, false, false, NOW() - INTERVAL '12 hours', NOW() - INTERVAL '12 hours'),
(48, '독고서', '마케터', '포트폴리오 작성 팁 #취업', '합격한 포트폴리오 실제 사례를 공유합니다. #취업 #포트폴리오', 'PUBLIC', 467, 82, 0, false, false, false, NOW() - INTERVAL '10 hours', NOW() - INTERVAL '10 hours'),
(49, '사공윤', 'SEO전문가', '코딩테스트 공부 루트 #코딩테스트', '비전공자가 3개월 만에 코테 통과한 방법입니다. #코딩테스트 #취업', 'PUBLIC', 723, 118, 0, false, false, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '8 hours'),
(50, '제갈호', '데이터사이언티스트', '주니어 개발자 이직 준비 #이직', '경력 1년차 이직 준비 과정을 상세히 공유합니다. #이직 #경력', 'PUBLIC', 512, 87, 0, false, false, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours'),

-- 임시저장 게시글 (draft)
(2, '김철수', '코딩마스터', '작성중인 Spring 튜토리얼 #Spring', '아직 작성 중입니다... #Spring #튜토리얼', 'PUBLIC', 0, 0, 0, true, false, false, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '5 hours'),
(18, '류준서', 'React개발자', 'React 프로젝트 기획 중 #React', '프로젝트 기획 단계입니다. #React #프로젝트', 'PUBLIC', 0, 0, 0, true, false, false, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '4 hours'),
(3, '이영희', '개발왕초보', 'JPA 성능 최적화 초안 #JPA', '초안 작성 중... #JPA #최적화', 'PUBLIC', 0, 0, 0, true, false, false, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '3 hours'),
(25, '석예원', 'Go언어러버', '블로그 이전 계획 #블로그', '블로그 이전 관련 메모... #블로그', 'PUBLIC', 0, 0, 0, true, false, false, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 hours'),
(30, '새 프로젝트 아이디어 #프로젝트', '아이디어 정리 중... #프로젝트 #기획', 0, 0, true, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '1 hour');

-- 추가 일반 게시글 30개
INSERT INTO board (user_id, author, nickname, title, content, status, view_count, like_count, comment_count, is_draft, is_pinned, is_important, created_at, updated_at) VALUES
(6, '강호준', '프론트엔드러', 'CSS Flexbox 완벽 가이드 #CSS', 'Flexbox로 모던 레이아웃을 마스터하세요. #CSS #프론트엔드 #레이아웃', 'PUBLIC', 234, 41, 0, false, false, false, NOW() - INTERVAL '50 minutes', NOW() - INTERVAL '50 minutes'),
(7, '윤서연', '백엔드개발자', 'RESTful API 설계 원칙 #API', 'REST API 설계 시 지켜야 할 핵심 원칙들입니다. #API #백엔드 #REST', 'PUBLIC', 312, 54, 0, false, false, false, NOW() - INTERVAL '45 minutes', NOW() - INTERVAL '45 minutes'),
(8, '임태희', '풀스택지망생', 'Git 브랜치 전략 비교 #Git', 'Git Flow, GitHub Flow 등 브랜치 전략을 비교합니다. #Git #협업', 'PUBLIC', 267, 47, 0, false, false, false, NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '40 minutes'),
(11, '한지우', 'AI연구원', 'Python 비동기 프로그래밍 #Python', 'asyncio를 활용한 비동기 프로그래밍 가이드입니다. #Python #비동기', 'PUBLIC', 198, 36, 0, false, false, false, NOW() - INTERVAL '35 minutes', NOW() - INTERVAL '35 minutes'),
(16, '신채원', 'iOS전문가', 'SwiftUI vs UIKit 비교 #iOS', 'iOS 개발 프레임워크 선택 가이드입니다. #iOS #Swift #모바일', 'PUBLIC', 223, 39, 0, false, false, false, NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes'),
(17, '홍시현', 'Android마스터', 'Android Jetpack Compose 입문 #Android', 'Compose로 선언적 UI를 구현하는 방법입니다. #Android #Kotlin', 'PUBLIC', 189, 33, 0, false, false, false, NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '25 minutes'),
(23, '탁은서', 'Django전문가', 'Django ORM 최적화 #Django', 'Django 쿼리를 최적화하는 실전 팁입니다. #Django #Python #ORM', 'PUBLIC', 245, 43, 0, false, false, false, NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '20 minutes'),
(24, '변건우', 'Flask개발자', 'Flask 마이크로서비스 구축 #Flask', 'Flask로 간단한 마이크로서비스를 만드는 방법입니다. #Flask #Python', 'PUBLIC', 176, 31, 0, false, false, false, NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '15 minutes'),
(26, '길민준', 'Rust전도사', 'Rust 소유권 시스템 이해하기 #Rust', 'Rust의 핵심 개념인 소유권을 쉽게 설명합니다. #Rust #시스템프로그래밍', 'PUBLIC', 201, 37, 0, false, false, false, NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '10 minutes'),
(27, '노서아', 'C++마스터', 'C++ 스마트 포인터 활용법 #C++', '메모리 관리를 안전하게 하는 스마트 포인터 가이드입니다. #C++ #메모리', 'PUBLIC', 167, 29, 0, false, false, false, NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '5 minutes'),
(28, '도연우', 'Kotlin개발자', 'Kotlin Coroutine 실전 활용 #Kotlin', 'Coroutine으로 비동기 처리를 우아하게 하는 방법입니다. #Kotlin #비동기', 'PUBLIC', 212, 38, 0, false, false, false, NOW() - INTERVAL '3 minutes', NOW() - INTERVAL '3 minutes'),
(29, '하시우', 'Swift전문가', 'Swift Combine 프레임워크 #Swift', 'Reactive Programming을 Swift로 구현하는 방법입니다. #Swift #Reactive', 'PUBLIC', 178, 32, 0, false, false, false, NOW() - INTERVAL '2 minutes', NOW() - INTERVAL '2 minutes'),
(31, '유다온', 'GraphQL전문가', 'GraphQL vs REST API #GraphQL', 'GraphQL의 장단점과 도입 시 고려사항입니다. #GraphQL #API', 'PUBLIC', 289, 50, 0, false, false, false, NOW() - INTERVAL '1 minute', NOW() - INTERVAL '1 minute'),
(32, '차하준', 'REST API마스터', 'gRPC 마이크로서비스 통신 #gRPC', 'gRPC로 고성능 서비스 간 통신을 구현하는 방법입니다. #gRPC #MSA', 'PUBLIC', 234, 42, 0, false, false, false, NOW(), NOW()),
(33, '추소율', 'MSA전문가', '서비스 메시 패턴 이해하기 #MSA', 'Istio, Linkerd 등 서비스 메시 개념과 활용법입니다. #MSA #아키텍처', 'PUBLIC', 198, 35, 0, false, false, false, NOW(), NOW()),
(37, '성시온', 'Azure마스터', 'Terraform 인프라 코드화 #IaC', 'Terraform으로 인프라를 코드로 관리하는 방법입니다. #IaC #Terraform', 'PUBLIC', 256, 45, 0, false, false, false, NOW(), NOW()),
(38, '양윤서', 'GCP전문가', 'Ansible 자동화 가이드 #자동화', 'Ansible로 서버 설정을 자동화하는 실전 가이드입니다. #자동화 #Ansible', 'PUBLIC', 223, 40, 0, false, false, false, NOW(), NOW()),
(40, '복하윤', 'Git전문가', '마이크로프론트엔드 아키텍처 #프론트엔드', 'MFE 개념과 실제 도입 사례를 공유합니다. #프론트엔드 #아키텍처', 'PUBLIC', 312, 55, 0, false, false, false, NOW(), NOW()),
(41, '설지호', '코드리뷰어', '코드 리뷰 문화 만들기 #협업', '효과적인 코드 리뷰 문화를 구축한 경험입니다. #협업 #코드리뷰', 'PUBLIC', 367, 63, 0, false, false, false, NOW(), NOW()),
(42, '옥서준', '테스트마스터', 'TDD 실천 가이드 #테스트', 'TDD로 개발 생산성을 높인 경험을 공유합니다. #테스트 #TDD #개발방법론', 'PUBLIC', 289, 51, 0, false, false, false, NOW(), NOW()),
(43, '엄다은', 'QA전문가', 'E2E 테스트 자동화 #테스트', 'Playwright로 E2E 테스트를 자동화하는 방법입니다. #테스트 #자동화', 'PUBLIC', 234, 43, 0, false, false, false, NOW(), NOW()),
(45, '남궁준', 'UX디자이너', '애자일 스크럼 도입기 #애자일', '스타트업에서 스크럼을 도입한 경험과 노하우입니다. #애자일 #스크럼 #PM', 'PUBLIC', 278, 48, 0, false, false, false, NOW(), NOW()),
(46, '선우아', 'UI디자이너', 'UX 개선으로 전환율 높이기 #UX', 'UX 개선으로 전환율을 2배 올린 사례입니다. #UX #디자인', 'PUBLIC', 345, 59, 0, false, false, false, NOW(), NOW()),
(47, '황보율', '기획자', '디자인 시스템 구축 가이드 #디자인', 'Figma와 Storybook으로 디자인 시스템을 만든 과정입니다. #디자인 #디자인시스템', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW()),
(10, '서준호', '데이터분석가', '머신러닝 입문 가이드 #AI', 'Python으로 시작하는 머신러닝 기초입니다. #AI #머신러닝 #Python', 'PUBLIC', 423, 72, 0, false, false, false, NOW(), NOW()),
(11, '한지우', 'AI연구원', '딥러닝 CNN 모델 이해하기 #딥러닝', 'CNN의 동작 원리를 쉽게 설명합니다. #딥러닝 #AI #CNN', 'PUBLIC', 367, 64, 0, false, false, false, NOW(), NOW()),
(12, '권수아', '클라우드엔지니어', '자연어 처리 BERT 활용 #NLP', 'BERT로 텍스트 분류를 구현하는 방법입니다. #NLP #AI #딥러닝', 'PUBLIC', 289, 50, 0, false, false, false, NOW(), NOW()),
(14, '조예린', '보안전문가', '웹 접근성 준수 가이드 #접근성', '모두를 위한 웹을 만들기 위한 접근성 가이드입니다. #접근성 #웹표준', 'PUBLIC', 256, 45, 0, false, false, false, NOW(), NOW()),
(15, '배현우', '모바일개발자', 'SEO 최적화 실전 팁 #SEO', '검색 엔진 최적화로 트래픽을 늘린 방법입니다. #SEO #마케팅', 'PUBLIC', 334, 58, 0, false, false, false, NOW(), NOW()),
(21, '남주아', 'Node.js개발자', 'WebAssembly 성능 최적화 #WebAssembly', 'WASM으로 웹 앱 성능을 극대화하는 방법입니다. #WebAssembly #성능', 'PUBLIC', 245, 43, 0, false, false, false, NOW(), NOW());
(22, '표지훈', 'Python마스터', 'PWA 오프라인 지원 구현 #PWA', 'Progressive Web App으로 오프라인 기능을 추가하는 방법입니다. #PWA #웹', 'PUBLIC', 278, 49, 0, false, false, false, NOW(), NOW());
(24, '변건우', 'Flask개발자', '블록체인 스마트 컨트랙트 #블록체인', 'Solidity로 스마트 컨트랙트를 작성하는 입문 가이드입니다. #블록체인 #Web3', 'PUBLIC', 312, 54, 0, false, false, false, NOW(), NOW()),
(25, '석예원', 'Go언어러버', 'NFT 마켓플레이스 개발기 #NFT', 'NFT 거래 플랫폼을 개발한 경험을 공유합니다. #NFT #블록체인 #Web3', 'PUBLIC', 389, 67, 0, false, false, false, NOW(), NOW()),
(26, '길민준', 'Rust전도사', '게임 개발 Unity 입문 #게임', 'Unity로 2D 게임을 만드는 초보자 가이드입니다. #게임 #Unity', 'PUBLIC', 267, 46, 0, false, false, false, NOW(), NOW());
(27, '노서아', 'C++마스터', 'Unreal Engine 5 신기능 #게임', 'UE5의 Nanite, Lumen 등 새 기술을 소개합니다. #게임 #Unreal', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW());
(30, '목지안', 'TypeScript러버', 'IoT 라즈베리파이 프로젝트 #IoT', '라즈베리파이로 홈 자동화를 구현한 프로젝트입니다. #IoT #라즈베리파이', 'PUBLIC', 234, 41, 0, false, false, false, NOW(), NOW()),
(31, '유다온', 'GraphQL전문가', '아두이노 센서 활용 가이드 #아두이노', '다양한 센서를 아두이노에 연결하는 방법입니다. #아두이노 #IoT', 'PUBLIC', 198, 35, 0, false, false, false, NOW(), NOW()),
(33, '추소율', 'MSA전문가', '사이드 프로젝트 아이디어 모음 #사이드프로젝트', '실제로 만들어볼 만한 사이드 프로젝트 아이디어들입니다. #사이드프로젝트 #아이디어', 'PUBLIC', 456, 78, 0, false, false, false, NOW(), NOW()),
(34, '피우진', 'Docker마스터', '개발자 영어 공부법 #영어', '기술 문서를 읽고 쓰는 영어 실력을 키우는 방법입니다. #영어 #공부', 'PUBLIC', 389, 67, 0, false, false, false, NOW(), NOW()),
(35, '함수빈', 'K8s전문가', '개발 블로그 운영 노하우 #블로그', '기술 블로그로 이직에 성공한 이야기입니다. #블로그 #브랜딩', 'PUBLIC', 512, 88, 0, false, false, false, NOW(), NOW());
(36, '곽하율', 'AWS전문가', '오픈소스 기여 시작하기 #오픈소스', '처음으로 오픈소스에 PR을 보낸 경험을 공유합니다. #오픈소스 #협업', 'PUBLIC', 367, 63, 0, false, false, false, NOW(), NOW()),
(38, '양윤서', 'GCP전문가', '번아웃 극복 경험담 #번아웃', '개발자 번아웃을 극복한 과정을 진솔하게 공유합니다. #번아웃 #멘탈케어', 'PUBLIC', 623, 102, 0, false, false, false, NOW(), NOW()),
(39, '민재원', 'CI/CD마스터', '재택근무 생산성 높이기 #재택근무', '재택근무에서 생산성을 유지하는 나만의 방법입니다. #재택근무 #생산성', 'PUBLIC', 445, 76, 0, false, false, false, NOW(), NOW()),
(40, '복하윤', 'Git전문가', '개발자 커리어 로드맵 #커리어', '주니어에서 시니어까지 커리어 성장 경험을 공유합니다. #커리어 #개발자', 'PUBLIC', 534, 91, 0, false, false, false, NOW(), NOW()),
(41, '설지호', '코드리뷰어', '회사에서 기술 스터디 운영하기 #스터디', '사내 기술 스터디를 성공적으로 운영한 노하우입니다. #스터디 #협업', 'PUBLIC', 289, 50, 0, false, false, false, NOW(), NOW()),
(42, '옥서준', '테스트마스터', '개발 컨퍼런스 참가 후기 #컨퍼런스', 'AWS re:Invent 참가 경험과 인사이트를 공유합니다. #컨퍼런스 #AWS', 'PUBLIC', 398, 68, 0, false, false, false, NOW(), NOW()),
(43, '엄다은', 'QA전문가', '해커톤 대회 우승기 #해커톤', '해커톤에서 우승한 아이디어와 개발 과정입니다. #해커톤 #대회', 'PUBLIC', 478, 82, 0, false, false, false, NOW(), NOW()),
(44, '예민성', 'PM지망생', '개발자 독서 추천 도서 #독서', '개발 실력 향상에 도움된 책들을 추천합니다. #독서 #책', 'PUBLIC', 356, 61, 0, false, false, false, NOW(), NOW()),
(45, '남궁준', 'UX디자이너', 'VS Code 확장 프로그램 추천 #VSCode', '생산성을 높여주는 VS Code 필수 확장들입니다. #VSCode #도구', 'PUBLIC', 412, 71, 0, false, false, false, NOW(), NOW()),
(46, '선우아', 'UI디자이너', 'IntelliJ IDEA 단축키 정리 #IntelliJ', 'IntelliJ 마스터를 위한 필수 단축키 모음입니다. #IntelliJ #단축키', 'PUBLIC', 334, 58, 0, false, false, false, NOW(), NOW()),
(47, '황보율', '기획자', '개발자 맥북 세팅 가이드 #맥북', '신입 개발자를 위한 맥북 개발 환경 세팅 가이드입니다. #맥북 #세팅', 'PUBLIC', 445, 77, 0, false, false, false, NOW(), NOW'),
(48, '독고서', '마케터', 'GitHub 프로필 꾸미기 #GitHub', '눈에 띄는 GitHub 프로필을 만드는 방법입니다. #GitHub #포트폴리오', 'PUBLIC', 389, 67, 0, false, false, false, NOW(), NOW()),
(49, '사공윤', 'SEO전문가', '알고리즘 문제 풀이 루틴 #알고리즘', '매일 알고리즘을 풀며 실력을 쌓은 방법입니다. #알고리즘 #공부', 'PUBLIC', 456, 79, 0, false, false, false, NOW(), NOW()),
(50, '제갈호', '데이터사이언티스트', '프로그래머스 Lv3 돌파 후기 #프로그래머스', '프로그래머스 레벨 3 문제를 풀며 배운 점들입니다. #프로그래머스 #코딩테스트', 'PUBLIC', 512, 88, 0, false, false, false, NOW(), NOW()),
(2, '김철수', '코딩마스터', '클린 코드 작성 원칙 #클린코드', '읽기 좋은 코드를 작성하는 핵심 원칙들입니다. #클린코드 #코딩', 'PUBLIC', 378, 65, 0, false, false, false, NOW(), NOW()),
(3, '이영희', '개발왕초보', '리팩토링 실전 사례 #리팩토링', '레거시 코드를 리팩토링한 실제 사례입니다. #리팩토링 #클린코드', 'PUBLIC', 334, 58, 0, false, false, false, NOW(), NOW()),
(4, '박민수', 'JavaLover', '디자인 패턴 실무 활용 #디자인패턴', '실제 프로젝트에서 활용한 디자인 패턴 사례들입니다. #디자인패턴 #아키텍처', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW()),
(5, '정다은', 'DB전문가', 'SOLID 원칙 쉽게 이해하기 #SOLID', '객체지향 설계의 5가지 원칙을 예제로 설명합니다. #SOLID #OOP', 'PUBLIC', 367, 63, 0, false, false, false, NOW(), NOW()),
(6, '강호준', '프론트엔드러', '함수형 프로그래밍 입문 #함수형', 'JavaScript로 배우는 함수형 프로그래밍 기초입니다. #함수형 #JavaScript', 'PUBLIC', 289, 50, 0, false, false, false, NOW(), NOW()),
(7, '윤서연', '백엔드개발자', '동시성 프로그래밍 패턴 #동시성', '멀티스레드 환경에서 안전한 코드를 작성하는 방법입니다. #동시성 #병렬처리', 'PUBLIC', 256, 45, 0, false, false, false, NOW(), NOW()),
(8, '임태희', '풀스택지망생', '메모리 누수 디버깅 #디버깅', 'Java 메모리 누수를 찾고 해결한 경험입니다. #디버깅 #Java #메모리', 'PUBLIC', 312, 54, 0, false, false, false, NOW(), NOW()),
(9, '오하늘', '알고리즘킬러', '성능 프로파일링 가이드 #성능', 'VisualVM으로 애플리케이션 성능을 분석하는 방법입니다. #성능 #프로파일링', 'PUBLIC', 234, 42, 0, false, false, false, NOW(), NOW()),
(10, '서준호', '데이터분석가', '로그 수집 시스템 구축 #로깅', 'ELK 스택으로 중앙 로그 시스템을 구축한 경험입니다. #로깅 #ELK', 'PUBLIC', 278, 48, 0, false, false, false, NOW(), NOW()),
(11, '한지우', 'AI연구원', '모니터링 시스템 구축 #모니터링', 'Prometheus + Grafana로 시스템을 모니터링하는 방법입니다. #모니터링 #DevOps', 'PUBLIC', 345, 59, 0, false, false, false, NOW(), NOW()),
(12, '권수아', '클라우드엔지니어', '장애 대응 매뉴얼 #장애', '실제 장애 상황에서 배운 대응 방법과 교훈입니다. #장애 #운영', 'PUBLIC', 423, 73, 0, false, false, false, NOW(), NOW()),
(13, '송민재', 'DevOps전문가', '무중단 배포 전략 #배포', 'Blue-Green 배포로 서비스 중단 없이 배포하는 방법입니다. #배포 #무중단', 'PUBLIC', 367, 64, 0, false, false, false, NOW(), NOW()),
(14, '조예린', '보안전문가', '카나리 배포 실전 가이드 #배포', '점진적 배포로 위험을 최소화하는 방법입니다. #배포 #카나리', 'PUBLIC', 289, 51, 0, false, false, false, NOW(), NOW()),
(15, '배현우', '모바일개발자', 'A/B 테스트 구현 및 분석 #AB테스트', 'A/B 테스트로 기능 효과를 검증한 사례입니다. #AB테스트 #데이터분석', 'PUBLIC', 312, 55, 0, false, false, false, NOW(), NOW()),
(16, '신채원', 'iOS전문가', '데이터 파이프라인 구축 #데이터', 'Airflow로 데이터 파이프라인을 자동화한 경험입니다. #데이터 #Airflow', 'PUBLIC', 256, 45, 0, false, false, false, NOW(), NOW()),
(17, '홍시현', 'Android마스터', '실시간 데이터 처리 시스템 #실시간', 'Kafka + Spark로 실시간 데이터를 처리하는 방법입니다. #실시간 #Kafka #Spark', 'PUBLIC', 334, 58, 0, false, false, false, NOW(), NOW()),
(18, '류준서', 'React개발자', '추천 시스템 알고리즘 #추천시스템', '협업 필터링으로 추천 엔진을 구현한 과정입니다. #추천시스템 #알고리즘', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW()),
(19, '문서윤', 'Vue마스터', '검색 랭킹 알고리즘 개선 #검색', '검색 품질을 높인 랭킹 알고리즘 개선 사례입니다. #검색 #알고리즘', 'PUBLIC', 267, 47, 0, false, false, false, NOW(), NOW()),
(20, '진도현', 'Angular전문가', 'OAuth 2.0 인증 구현 #OAuth', 'OAuth 2.0으로 소셜 로그인을 구현하는 방법입니다. #OAuth #인증', 'PUBLIC', 389, 67, 0, false, false, false, NOW(), NOW()),
(21, '남주아', 'Node.js개발자', 'SSO 시스템 구축기 #SSO', '여러 서비스를 하나의 계정으로 통합한 경험입니다. #SSO #인증', 'PUBLIC', 312, 54, 0, false, false, false, NOW(), NOW()),
(22, '표지훈', 'Python마스터', 'CORS 이슈 해결 가이드 #CORS', 'CORS 문제를 이해하고 해결하는 방법입니다. #CORS #웹', 'PUBLIC', 445, 77, 0, false, false, false, NOW(), NOW()),
(23, '탁은서', 'Django전문가', 'XSS 공격 방어 전략 #보안', 'XSS 취약점을 찾고 막는 방법입니다. #보안 #XSS', 'PUBLIC', 356, 62, 0, false, false, false, NOW(), NOW()),
(24, '변건우', 'Flask개발자', 'SQL Injection 방어 #보안', 'SQL Injection 공격을 예방하는 코딩 방법입니다. #보안 #SQL', 'PUBLIC', 378, 65, 0, false, false, false, NOW(), NOW()),
(25, '석예원', 'Go언어러버', 'HTTPS 적용 완벽 가이드 #HTTPS', 'Let''s Encrypt로 무료 SSL 인증서를 적용하는 방법입니다. #HTTPS #보안', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW()),
(26, '길민준', 'Rust전도사', 'API Rate Limiting 구현 #API', 'API 남용을 방지하는 Rate Limiting 구현 사례입니다. #API #보안', 'PUBLIC', 267, 47, 0, false, false, false, NOW(), NOW()),
(27, '노서아', 'C++마스터', 'Webhook 시스템 구축 #Webhook', '이벤트 기반 Webhook 시스템을 만든 경험입니다. #Webhook #API', 'PUBLIC', 234, 42, 0, false, false, false, NOW(), NOW()),
(28, '도연우', 'Kotlin개발자', '페이지네이션 최적화 #최적화', '대용량 데이터의 페이지네이션을 최적화한 방법입니다. #최적화 #DB', 'PUBLIC', 312, 55, 0, false, false, false, NOW(), NOW()),
(29, '하시우', 'Swift전문가', '무한 스크롤 구현 #프론트엔드', 'React로 효율적인 무한 스크롤을 구현하는 방법입니다. #프론트엔드 #React', 'PUBLIC', 289, 51, 0, false, false, false, NOW(), NOW()),
(30, '목지안', 'TypeScript러버', '이미지 최적화 전략 #최적화', '웹 성능을 높이는 이미지 최적화 기법들입니다. #최적화 #성능', 'PUBLIC', 345, 60, 0, false, false, false, NOW(), NOW()),
(31, '유다온', 'GraphQL전문가', 'CDN 설정 및 캐시 전략 #CDN', 'CloudFront로 전 세계 사용자에게 빠른 서비스를 제공하는 방법입니다. #CDN #AWS', 'PUBLIC', 298, 53, 0, false, false, false, NOW(), NOW()),
(32, '차하준', 'REST API마스터', '웹 폰트 로딩 최적화 #폰트', 'FOUT, FOIT를 방지하고 폰트를 빠르게 로딩하는 방법입니다. #폰트 #성능', 'PUBLIC', 256, 46, 0, false, false, false, NOW(), NOW()),
(33, '추소율', 'MSA전문가', '번들 사이즈 최적화 #빌드', 'Webpack으로 번들 크기를 절반으로 줄인 방법입니다. #빌드 #Webpack', 'PUBLIC', 334, 59, 0, false, false, false, NOW(), NOW()),
(34, '피우진', 'Docker마스터', '코드 스플리팅 전략 #최적화', 'React 앱의 초기 로딩 속도를 개선한 경험입니다. #최적화 #React', 'PUBLIC', 312, 56, 0, false, false, false, NOW(), NOW()),
(35, '함수빈', 'K8s전문가', 'Tree Shaking 완벽 가이드 #빌드', '사용하지 않는 코드를 제거하는 Tree Shaking 가이드입니다. #빌드 #최적화', 'PUBLIC', 278, 49, 0, false, false, false, NOW(), NOW()),
(36, '곽하율', 'AWS전문가', '레거시 코드 마이그레이션 #마이그레이션', 'Angular.js를 React로 마이그레이션한 대규모 프로젝트 경험입니다. #마이그레이션 #React', 'PUBLIC', 423, 74, 0, false, false, false, NOW(), NOW()),
(37, '성시온', 'Azure마스터', 'Monorepo 구축 가이드 #Monorepo', 'Turborepo로 모노레포를 구축한 경험입니다. #Monorepo #도구', 'PUBLIC', 289, 51, 0, false, false, false, NOW(), NOW()),
(38, '양윤서', 'GCP전문가', 'Micro Frontend 아키텍처 #아키텍처', '마이크로 프론트엔드로 팀 간 협업을 개선한 사례입니다. #아키텍처 #프론트엔드', 'PUBLIC', 367, 64, 0, false, false, false, NOW(), NOW()),
(39, '민재원', 'CI/CD마스터', '상태 관리 라이브러리 비교 #상태관리', 'Redux, MobX, Zustand 등 상태 관리 솔루션을 비교합니다. #상태관리 #React', 'PUBLIC', 398, 69, 0, false, false, false, NOW(), NOW()),
(40, '복하윤', 'Git전문가', '글로벌 상태 vs 로컬 상태 #상태관리', '상태를 어디에 저장할지 결정하는 기준을 제시합니다. #상태관리 #아키텍처', 'PUBLIC', 312, 56, 0, false, false, false, NOW(), NOW()),
(41, '설지호', '코드리뷰어', 'React Server Components #React', 'RSC의 개념과 사용 사례를 설명합니다. #React #서버컴포넌트', 'PUBLIC', 445, 78, 0, false, false, false, NOW(), NOW()),
(42, '옥서준', '테스트마스터', 'Suspense와 Concurrent Mode #React', 'React 18의 새로운 기능들을 실전에서 활용하는 방법입니다. #React #Suspense', 'PUBLIC', 378, 66, 0, false, false, false, NOW(), NOW()),
(43, '엄다은', 'QA전문가', 'Custom Hook 설계 패턴 #React', '재사용 가능한 커스텀 훅을 만드는 방법입니다. #React #Hook', 'PUBLIC', 334, 59, 0, false, false, false, NOW(), NOW()),
(44, '예민성', 'PM지망생', 'React 성능 최적화 체크리스트 #React', 'React 앱의 성능을 극대화하는 필수 체크리스트입니다. #React #성능', 'PUBLIC', 456, 80, 0, false, false, false, NOW(), NOW()),
(45, '남궁준', 'UX디자이너', 'Context API vs Redux #React', '상황에 따른 상태 관리 도구 선택 가이드입니다. #React #상태관리', 'PUBLIC', 389, 68, 0, false, false, false, NOW(), NOW()),
(46, '선우아', 'UI디자이너', 'React Testing Library 활용 #테스트', 'RTL로 효과적인 컴포넌트 테스트를 작성하는 방법입니다. #테스트 #React', 'PUBLIC', 312, 55, 0, false, false, false, NOW(), NOW()),
(47, '황보율', '기획자', 'Jest Mock 완벽 가이드 #테스트', 'Jest로 모의 객체를 만들고 테스트하는 방법입니다. #테스트 #Jest', 'PUBLIC', 278, 49, 0, false, false, false, NOW(), NOW()),
(48, '독고서', '마케터', 'E2E 테스트 시나리오 작성 #테스트', '사용자 관점의 효과적인 E2E 테스트 시나리오입니다. #테스트 #E2E', 'PUBLIC', 298, 52, 0, false, false, false, NOW(), NOW()),
(49, '사공윤', 'SEO전문가', '테스트 커버리지 높이기 #테스트', '의미 있는 테스트 커버리지를 달성하는 방법입니다. #테스트 #TDD', 'PUBLIC', 334, 58, 0, false, false, false, NOW(), NOW'),
(50, '제갈호', '데이터사이언티스트', '통합 테스트 vs 단위 테스트 #테스트', '테스트 전략을 수립하는 기준과 사례입니다. #테스트 #전략', 'PUBLIC', 367, 64, 0, false, false, false, NOW(), NOW()),
(2, '김철수', '코딩마스터', 'BDD로 테스트 작성하기 #BDD', '행위 주도 개발로 테스트를 작성하는 방법입니다. #BDD #테스트', 'PUBLIC', 289, 51, 0, false, false, false, NOW(), NOW()),
(3, '이영희', '개발왕초보', 'Snapshot 테스트 활용법 #테스트', 'UI 변경을 추적하는 스냅샷 테스트 가이드입니다. #테스트 #React', 'PUBLIC', 256, 46, 0, false, false, false, NOW(), NOW()),
(4, '박민수', 'JavaLover', '성능 테스트 자동화 #테스트', 'JMeter로 부하 테스트를 자동화한 경험입니다. #테스트 #성능', 'PUBLIC', 312, 55, 0, false, false, false, NOW(), NOW()),
(5, '정다은', 'DB전문가', '보안 테스트 가이드 #보안', 'OWASP Top 10을 점검하는 보안 테스트 방법입니다. #보안 #테스트', 'PUBLIC', 345, 60, 0, false, false, false, NOW(), NOW()),
(6, '강호준', '프론트엔드러', 'UI/UX 테스트 자동화 #테스트', 'Percy로 시각적 회귀 테스트를 자동화하는 방법입니다. #테스트 #UI', 'PUBLIC', 278, 49, 0, false, false, false, NOW(), NOW());
