-- 추가 게시글 100개 생성

INSERT INTO board (user_id, author, nickname, title, content, status, view_count, like_count, comment_count, is_draft, is_pinned, is_important, created_at, updated_at) VALUES
-- 최신 기술 트렌드 (1-20)
(2, '김철수', '코딩마스터', 'AI 코딩 어시스턴트 활용법 #AI #개발도구', 'GitHub Copilot, Claude 등 AI 코딩 도구를 효과적으로 활용하는 방법입니다. #AI #개발도구 #생산성', 'PUBLIC', 523, 89, 0, false, false, false, NOW() - INTERVAL '29 days', NOW() - INTERVAL '29 days'),
(3, '이영희', '개발왕초보', 'ChatGPT API 활용 프로젝트 #AI #API', 'OpenAI API를 활용한 챗봇 서비스 개발기입니다. #AI #API #프로젝트', 'PUBLIC', 467, 78, 0, false, false, false, NOW() - INTERVAL '28 days', NOW() - INTERVAL '28 days'),
(4, '박민수', 'JavaLover', 'Spring AI 프레임워크 소개 #Spring #AI', 'Spring 생태계에서 AI를 활용하는 새로운 방법입니다. #Spring #AI #Java', 'PUBLIC', 389, 65, 0, false, false, false, NOW() - INTERVAL '27 days', NOW() - INTERVAL '27 days'),
(5, '정다은', 'DB전문가', 'Vector DB 선택 가이드 #DB #AI', 'Pinecone, Weaviate, Chroma 등 벡터 DB를 비교 분석합니다. #DB #AI #벡터', 'PUBLIC', 412, 71, 0, false, false, false, NOW() - INTERVAL '26 days', NOW() - INTERVAL '26 days'),
(6, '강호준', '프론트엔드러', 'LangChain 실전 가이드 #AI #Python', 'LangChain으로 RAG 시스템을 구축하는 방법입니다. #AI #Python #LangChain', 'PUBLIC', 534, 92, 0, false, false, false, NOW() - INTERVAL '25 days', NOW() - INTERVAL '25 days'),
(7, '윤서연', '백엔드개발자', 'Stable Diffusion 로컬 설치 #AI #이미지', 'Stable Diffusion을 로컬에서 실행하는 완벽 가이드입니다. #AI #이미지 #딥러닝', 'PUBLIC', 623, 105, 0, false, false, false, NOW() - INTERVAL '24 days', NOW() - INTERVAL '24 days'),
(8, '임태희', '풀스택지망생', 'Hugging Face 모델 파인튜닝 #AI #NLP', '사전 학습 모델을 내 데이터로 미세 조정하는 방법입니다. #AI #NLP #파인튜닝', 'PUBLIC', 356, 61, 0, false, false, false, NOW() - INTERVAL '23 days', NOW() - INTERVAL '23 days'),
(9, '오하늘', '알고리즘킬러', 'MLOps 파이프라인 구축 #MLOps #DevOps', 'ML 모델의 배포와 운영을 자동화하는 방법입니다. #MLOps #DevOps #AI', 'PUBLIC', 445, 76, 0, false, false, false, NOW() - INTERVAL '22 days', NOW() - INTERVAL '22 days'),
(10, '서준호', '데이터분석가', 'Feature Store 도입기 #데이터 #ML', 'Feast로 피처 스토어를 구축한 경험을 공유합니다. #데이터 #ML #피처엔지니어링', 'PUBLIC', 312, 54, 0, false, false, false, NOW() - INTERVAL '21 days', NOW() - INTERVAL '21 days'),
(11, '한지우', 'AI연구원', 'LLM 프롬프트 엔지니어링 #AI #프롬프트', '효과적인 프롬프트를 작성하는 실전 기법들입니다. #AI #프롬프트 #LLM', 'PUBLIC', 567, 97, 0, false, false, false, NOW() - INTERVAL '20 days', NOW() - INTERVAL '20 days'),
(12, '권수아', '클라우드엔지니어', 'GPU 클라우드 비용 최적화 #클라우드 #GPU', 'AI 워크로드의 클라우드 비용을 절감하는 방법입니다. #클라우드 #GPU #비용', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '19 days', NOW() - INTERVAL '19 days'),
(13, '송민재', 'DevOps전문가', 'Edge AI 배포 전략 #Edge #AI', 'AI 모델을 엣지 디바이스에 배포하는 방법입니다. #Edge #AI #배포', 'PUBLIC', 298, 52, 0, false, false, false, NOW() - INTERVAL '18 days', NOW() - INTERVAL '18 days'),
(14, '조예린', '보안전문가', 'AI 모델 보안 가이드 #AI #보안', 'ML 모델의 보안 취약점과 대응 방법입니다. #AI #보안 #MLSec', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '17 days', NOW() - INTERVAL '17 days'),
(15, '배현우', '모바일개발자', 'TensorFlow Lite 모바일 적용 #TensorFlow #모바일', '모바일 앱에 온디바이스 AI를 적용하는 방법입니다. #TensorFlow #모바일 #AI', 'PUBLIC', 345, 59, 0, false, false, false, NOW() - INTERVAL '16 days', NOW() - INTERVAL '16 days'),
(16, '신채원', 'iOS전문가', 'Core ML 활용 가이드 #iOS #ML', 'Apple Core ML로 iOS 앱에 AI를 추가하는 방법입니다. #iOS #ML #Apple', 'PUBLIC', 267, 47, 0, false, false, false, NOW() - INTERVAL '15 days', NOW() - INTERVAL '15 days'),
(17, '홍시현', 'Android마스터', 'MediaPipe 실시간 처리 #Android #AI', 'MediaPipe로 실시간 얼굴 인식을 구현하는 방법입니다. #Android #AI #MediaPipe', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '14 days', NOW() - INTERVAL '14 days'),
(18, '류준서', 'React개발자', 'Vercel AI SDK 활용법 #AI #React', 'Next.js에서 AI 스트리밍을 구현하는 방법입니다. #AI #React #Vercel', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '13 days', NOW() - INTERVAL '13 days'),
(19, '문서윤', 'Vue마스터', 'AI 이미지 생성 서비스 구축 #AI #프로젝트', 'DALL-E API로 이미지 생성 서비스를 만든 경험입니다. #AI #프로젝트 #DALLE', 'PUBLIC', 534, 91, 0, false, false, false, NOW() - INTERVAL '12 days', NOW() - INTERVAL '12 days'),
(20, '진도현', 'Angular전문가', 'AI 음성 인식 앱 개발 #AI #음성', 'Whisper API로 음성 인식 기능을 구현하는 방법입니다. #AI #음성 #Whisper', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '11 days', NOW() - INTERVAL '11 days'),

-- 백엔드 심화 (21-40)
(21, '남주아', 'Node.js개발자', 'Event Sourcing 패턴 구현 #아키텍처 #DDD', '이벤트 소싱으로 데이터 변경 이력을 관리하는 방법입니다. #아키텍처 #DDD #이벤트소싱', 'PUBLIC', 378, 65, 0, false, false, false, NOW() - INTERVAL '10 days', NOW() - INTERVAL '10 days'),
(22, '표지훈', 'Python마스터', 'CQRS 실전 적용기 #CQRS #아키텍처', '명령과 조회를 분리하여 성능을 개선한 사례입니다. #CQRS #아키텍처 #성능', 'PUBLIC', 312, 54, 0, false, false, false, NOW() - INTERVAL '9 days 20 hours', NOW() - INTERVAL '9 days 20 hours'),
(23, '탁은서', 'Django전문가', 'Saga 패턴으로 분산 트랜잭션 #MSA #Saga', '마이크로서비스 간 트랜잭션을 관리하는 방법입니다. #MSA #Saga #분산시스템', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '9 days 16 hours', NOW() - INTERVAL '9 days 16 hours'),
(24, '변건우', 'Flask개발자', 'Outbox 패턴 구현하기 #MSA #이벤트', '이벤트 유실 없이 안전하게 발행하는 방법입니다. #MSA #이벤트 #Outbox', 'PUBLIC', 289, 50, 0, false, false, false, NOW() - INTERVAL '9 days 12 hours', NOW() - INTERVAL '9 days 12 hours'),
(25, '석예원', 'Go언어러버', 'Go 동시성 패턴 마스터 #Go #동시성', 'Go의 goroutine과 channel을 활용한 동시성 패턴입니다. #Go #동시성 #병렬처리', 'PUBLIC', 456, 78, 0, false, false, false, NOW() - INTERVAL '9 days 8 hours', NOW() - INTERVAL '9 days 8 hours'),
(26, '길민준', 'Rust전도사', 'Rust 비동기 프로그래밍 #Rust #비동기', 'Tokio로 고성능 비동기 서버를 만드는 방법입니다. #Rust #비동기 #Tokio', 'PUBLIC', 367, 63, 0, false, false, false, NOW() - INTERVAL '9 days 4 hours', NOW() - INTERVAL '9 days 4 hours'),
(27, '노서아', 'C++마스터', 'Quarkus vs Spring Boot #Java #비교', '클라우드 네이티브 프레임워크를 비교 분석합니다. #Java #비교 #Quarkus', 'PUBLIC', 398, 68, 0, false, false, false, NOW() - INTERVAL '9 days', NOW() - INTERVAL '9 days'),
(28, '도연우', 'Kotlin개발자', 'Ktor 프레임워크 입문 #Kotlin #Ktor', 'Kotlin으로 경량 웹 서버를 만드는 방법입니다. #Kotlin #Ktor #웹서버', 'PUBLIC', 278, 48, 0, false, false, false, NOW() - INTERVAL '8 days 20 hours', NOW() - INTERVAL '8 days 20 hours'),
(29, '하시우', 'Swift전문가', 'Vapor 서버사이드 Swift #Swift #백엔드', 'Swift로 백엔드 API를 개발하는 방법입니다. #Swift #백엔드 #Vapor', 'PUBLIC', 234, 42, 0, false, false, false, NOW() - INTERVAL '8 days 16 hours', NOW() - INTERVAL '8 days 16 hours'),
(30, '목지안', 'TypeScript러버', 'NestJS 심화 가이드 #NestJS #TypeScript', 'NestJS로 엔터프라이즈급 API를 개발하는 방법입니다. #NestJS #TypeScript #백엔드', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '8 days 12 hours', NOW() - INTERVAL '8 days 12 hours'),
(31, '유다온', 'GraphQL전문가', 'Prisma ORM 완벽 가이드 #Prisma #ORM', 'Type-safe ORM으로 DB 작업을 효율화하는 방법입니다. #Prisma #ORM #TypeScript', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '8 days 8 hours', NOW() - INTERVAL '8 days 8 hours'),
(32, '차하준', 'REST API마스터', 'Drizzle ORM 마이그레이션 #Drizzle #ORM', 'Prisma에서 Drizzle로 마이그레이션한 경험입니다. #Drizzle #ORM #마이그레이션', 'PUBLIC', 312, 54, 0, false, false, false, NOW() - INTERVAL '8 days 4 hours', NOW() - INTERVAL '8 days 4 hours'),
(33, '추소율', 'MSA전문가', 'API Gateway 패턴 구현 #MSA #Gateway', 'Kong, APISIX로 API Gateway를 구축하는 방법입니다. #MSA #Gateway #Kong', 'PUBLIC', 356, 61, 0, false, false, false, NOW() - INTERVAL '8 days', NOW() - INTERVAL '8 days'),
(34, '피우진', 'Docker마스터', 'Service Mesh 심화 #MSA #Istio', 'Istio로 트래픽 관리와 보안을 구현하는 방법입니다. #MSA #Istio #ServiceMesh', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '7 days 20 hours', NOW() - INTERVAL '7 days 20 hours'),
(35, '함수빈', 'K8s전문가', 'Dapr 분산 애플리케이션 #Dapr #MSA', 'Dapr로 분산 시스템을 쉽게 개발하는 방법입니다. #Dapr #MSA #분산시스템', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '7 days 16 hours', NOW() - INTERVAL '7 days 16 hours'),
(36, '곽하율', 'AWS전문가', 'Temporal 워크플로우 엔진 #Temporal #워크플로우', 'Temporal로 복잡한 비즈니스 로직을 관리하는 방법입니다. #Temporal #워크플로우 #MSA', 'PUBLIC', 334, 58, 0, false, false, false, NOW() - INTERVAL '7 days 12 hours', NOW() - INTERVAL '7 days 12 hours'),
(37, '성시온', 'Azure마스터', 'Serverless Framework 활용 #Serverless #AWS', '서버리스 아키텍처를 효율적으로 관리하는 방법입니다. #Serverless #AWS #Lambda', 'PUBLIC', 378, 65, 0, false, false, false, NOW() - INTERVAL '7 days 8 hours', NOW() - INTERVAL '7 days 8 hours'),
(38, '양윤서', 'GCP전문가', 'Firebase Functions 최적화 #Firebase #Serverless', 'Firebase Cloud Functions 성능을 높이는 방법입니다. #Firebase #Serverless #GCP', 'PUBLIC', 267, 47, 0, false, false, false, NOW() - INTERVAL '7 days 4 hours', NOW() - INTERVAL '7 days 4 hours'),
(39, '민재원', 'CI/CD마스터', 'Supabase 백엔드 구축 #Supabase #BaaS', 'Supabase로 빠르게 백엔드를 구축하는 방법입니다. #Supabase #BaaS #PostgreSQL', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '7 days', NOW() - INTERVAL '7 days'),
(40, '복하윤', 'Git전문가', 'Planetscale 무중단 스키마 변경 #DB #MySQL', 'Planetscale로 다운타임 없이 스키마를 변경하는 방법입니다. #DB #MySQL #Planetscale', 'PUBLIC', 356, 62, 0, false, false, false, NOW() - INTERVAL '6 days 20 hours', NOW() - INTERVAL '6 days 20 hours'),

-- 프론트엔드 심화 (41-60)
(41, '설지호', '코드리뷰어', 'React 19 새로운 기능 #React #프론트엔드', 'React 19의 주요 변경사항과 마이그레이션 가이드입니다. #React #프론트엔드 #React19', 'PUBLIC', 567, 97, 0, false, false, false, NOW() - INTERVAL '6 days 16 hours', NOW() - INTERVAL '6 days 16 hours'),
(42, '옥서준', '테스트마스터', 'Next.js 14 App Router #Next #React', 'App Router로 마이그레이션한 경험을 공유합니다. #Next #React #AppRouter', 'PUBLIC', 489, 84, 0, false, false, false, NOW() - INTERVAL '6 days 12 hours', NOW() - INTERVAL '6 days 12 hours'),
(43, '엄다은', 'QA전문가', 'Remix vs Next.js #Remix #비교', '풀스택 프레임워크를 비교 분석합니다. #Remix #비교 #프론트엔드', 'PUBLIC', 398, 68, 0, false, false, false, NOW() - INTERVAL '6 days 8 hours', NOW() - INTERVAL '6 days 8 hours'),
(44, '예민성', 'PM지망생', 'Astro 정적 사이트 생성 #Astro #SSG', 'Astro로 빠른 정적 사이트를 만드는 방법입니다. #Astro #SSG #정적사이트', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '6 days 4 hours', NOW() - INTERVAL '6 days 4 hours'),
(45, '남궁준', 'UX디자이너', 'SolidJS 반응형 프리미티브 #SolidJS #프론트엔드', '가벼운 반응형 UI 라이브러리 SolidJS 입문입니다. #SolidJS #프론트엔드 #반응형', 'PUBLIC', 267, 47, 0, false, false, false, NOW() - INTERVAL '6 days', NOW() - INTERVAL '6 days'),
(46, '선우아', 'UI디자이너', 'Svelte 5 Runes 사용법 #Svelte #Runes', 'Svelte 5의 새로운 반응성 시스템을 소개합니다. #Svelte #Runes #프론트엔드', 'PUBLIC', 345, 60, 0, false, false, false, NOW() - INTERVAL '5 days 20 hours', NOW() - INTERVAL '5 days 20 hours'),
(47, '황보율', '기획자', 'Qwik 레저메이블 앱 #Qwik #성능', '제로 하이드레이션으로 초고속 앱을 만드는 방법입니다. #Qwik #성능 #프론트엔드', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '5 days 16 hours', NOW() - INTERVAL '5 days 16 hours'),
(48, '독고서', '마케터', 'HTMX 하이퍼미디어 앱 #HTMX #심플', 'JavaScript 없이 동적 UI를 만드는 방법입니다. #HTMX #심플 #백엔드', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '5 days 12 hours', NOW() - INTERVAL '5 days 12 hours'),
(49, '사공윤', 'SEO전문가', 'Alpine.js 경량 인터랙션 #AlpineJS #경량', '가벼운 인터랙티브 컴포넌트를 만드는 방법입니다. #AlpineJS #경량 #프론트엔드', 'PUBLIC', 234, 42, 0, false, false, false, NOW() - INTERVAL '5 days 8 hours', NOW() - INTERVAL '5 days 8 hours'),
(50, '제갈호', '데이터사이언티스트', 'Tailwind CSS v4 새 기능 #Tailwind #CSS', 'Tailwind CSS 최신 버전의 변경사항입니다. #Tailwind #CSS #스타일링', 'PUBLIC', 512, 88, 0, false, false, false, NOW() - INTERVAL '5 days 4 hours', NOW() - INTERVAL '5 days 4 hours'),
(2, '김철수', '코딩마스터', 'shadcn/ui 컴포넌트 활용 #shadcn #UI', 'Copy & Paste 방식의 UI 컴포넌트 활용법입니다. #shadcn #UI #React', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '5 days', NOW() - INTERVAL '5 days'),
(3, '이영희', '개발왕초보', 'Radix UI 접근성 컴포넌트 #Radix #접근성', '접근성이 보장된 헤드리스 UI 라이브러리입니다. #Radix #접근성 #UI', 'PUBLIC', 356, 62, 0, false, false, false, NOW() - INTERVAL '4 days 20 hours', NOW() - INTERVAL '4 days 20 hours'),
(4, '박민수', 'JavaLover', 'Framer Motion 애니메이션 #Framer #애니메이션', 'React에서 부드러운 애니메이션을 구현하는 방법입니다. #Framer #애니메이션 #React', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '4 days 16 hours', NOW() - INTERVAL '4 days 16 hours'),
(5, '정다은', 'DB전문가', 'GSAP 스크롤 트리거 #GSAP #애니메이션', '스크롤 기반 인터랙션을 구현하는 방법입니다. #GSAP #애니메이션 #스크롤', 'PUBLIC', 298, 52, 0, false, false, false, NOW() - INTERVAL '4 days 12 hours', NOW() - INTERVAL '4 days 12 hours'),
(6, '강호준', '프론트엔드러', 'Lottie 애니메이션 적용 #Lottie #애니메이션', 'After Effects 애니메이션을 웹에 적용하는 방법입니다. #Lottie #애니메이션 #웹', 'PUBLIC', 267, 47, 0, false, false, false, NOW() - INTERVAL '4 days 8 hours', NOW() - INTERVAL '4 days 8 hours'),
(7, '윤서연', '백엔드개발자', 'Three.js 3D 웹 개발 #ThreeJS #3D', 'WebGL로 3D 그래픽을 구현하는 입문 가이드입니다. #ThreeJS #3D #WebGL', 'PUBLIC', 456, 79, 0, false, false, false, NOW() - INTERVAL '4 days 4 hours', NOW() - INTERVAL '4 days 4 hours'),
(8, '임태희', '풀스택지망생', 'React Three Fiber 활용 #R3F #3D', 'React에서 Three.js를 선언적으로 사용하는 방법입니다. #R3F #3D #React', 'PUBLIC', 378, 65, 0, false, false, false, NOW() - INTERVAL '4 days', NOW() - INTERVAL '4 days'),
(9, '오하늘', '알고리즘킬러', 'D3.js 데이터 시각화 #D3 #시각화', 'D3.js로 인터랙티브 차트를 만드는 방법입니다. #D3 #시각화 #데이터', 'PUBLIC', 345, 60, 0, false, false, false, NOW() - INTERVAL '3 days 20 hours', NOW() - INTERVAL '3 days 20 hours'),
(10, '서준호', '데이터분석가', 'Chart.js vs ECharts 비교 #차트 #시각화', '프론트엔드 차트 라이브러리를 비교 분석합니다. #차트 #시각화 #프론트엔드', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '3 days 16 hours', NOW() - INTERVAL '3 days 16 hours'),
(11, '한지우', 'AI연구원', 'Web Animation API 활용 #WAAPI #애니메이션', 'CSS와 JavaScript를 결합한 고성능 애니메이션입니다. #WAAPI #애니메이션 #성능', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '3 days 12 hours', NOW() - INTERVAL '3 days 12 hours'),

-- 클라우드/인프라 심화 (61-80)
(12, '권수아', '클라우드엔지니어', 'AWS CDK 인프라 코드화 #AWS #CDK', 'TypeScript로 AWS 인프라를 정의하는 방법입니다. #AWS #CDK #IaC', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '3 days 8 hours', NOW() - INTERVAL '3 days 8 hours'),
(13, '송민재', 'DevOps전문가', 'Pulumi vs Terraform 비교 #IaC #비교', 'IaC 도구를 비교하고 선택 기준을 제시합니다. #IaC #비교 #인프라', 'PUBLIC', 367, 64, 0, false, false, false, NOW() - INTERVAL '3 days 4 hours', NOW() - INTERVAL '3 days 4 hours'),
(14, '조예린', '보안전문가', 'GitOps Flux 도입기 #GitOps #Flux', 'Flux로 GitOps 워크플로우를 구축한 경험입니다. #GitOps #Flux #K8s', 'PUBLIC', 298, 52, 0, false, false, false, NOW() - INTERVAL '3 days', NOW() - INTERVAL '3 days'),
(15, '배현우', '모바일개발자', 'ArgoCD 배포 자동화 #ArgoCD #GitOps', 'ArgoCD로 쿠버네티스 배포를 자동화하는 방법입니다. #ArgoCD #GitOps #K8s', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '2 days 20 hours', NOW() - INTERVAL '2 days 20 hours'),
(16, '신채원', 'iOS전문가', 'Helm 차트 작성 가이드 #Helm #K8s', 'Kubernetes 앱을 패키징하는 Helm 차트 작성법입니다. #Helm #K8s #패키징', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '2 days 16 hours', NOW() - INTERVAL '2 days 16 hours'),
(17, '홍시현', 'Android마스터', 'Kustomize 환경별 설정 #Kustomize #K8s', 'Kustomize로 환경별 K8s 리소스를 관리하는 방법입니다. #Kustomize #K8s #설정', 'PUBLIC', 256, 46, 0, false, false, false, NOW() - INTERVAL '2 days 12 hours', NOW() - INTERVAL '2 days 12 hours'),
(18, '류준서', 'React개발자', 'EKS Fargate 서버리스 K8s #EKS #Fargate', 'AWS에서 서버리스 쿠버네티스를 운영하는 방법입니다. #EKS #Fargate #AWS', 'PUBLIC', 378, 66, 0, false, false, false, NOW() - INTERVAL '2 days 8 hours', NOW() - INTERVAL '2 days 8 hours'),
(19, '문서윤', 'Vue마스터', 'GKE Autopilot 활용법 #GKE #Autopilot', 'Google Cloud의 관리형 K8s 서비스 활용법입니다. #GKE #Autopilot #GCP', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '2 days 4 hours', NOW() - INTERVAL '2 days 4 hours'),
(20, '진도현', 'Angular전문가', 'AKS 네트워킹 심화 #AKS #네트워킹', 'Azure Kubernetes Service 네트워크 설정 가이드입니다. #AKS #네트워킹 #Azure', 'PUBLIC', 234, 43, 0, false, false, false, NOW() - INTERVAL '2 days', NOW() - INTERVAL '2 days'),
(21, '남주아', 'Node.js개발자', 'K8s HPA 오토스케일링 #K8s #오토스케일링', 'Horizontal Pod Autoscaler로 자동 확장하는 방법입니다. #K8s #오토스케일링 #스케일링', 'PUBLIC', 345, 60, 0, false, false, false, NOW() - INTERVAL '1 day 20 hours', NOW() - INTERVAL '1 day 20 hours'),
(22, '표지훈', 'Python마스터', 'Karpenter 노드 자동화 #Karpenter #K8s', 'Karpenter로 노드 프로비저닝을 자동화하는 방법입니다. #Karpenter #K8s #AWS', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '1 day 16 hours', NOW() - INTERVAL '1 day 16 hours'),
(23, '탁은서', 'Django전문가', 'Knative 서버리스 컨테이너 #Knative #서버리스', 'K8s 위에서 서버리스를 구현하는 방법입니다. #Knative #서버리스 #K8s', 'PUBLIC', 267, 48, 0, false, false, false, NOW() - INTERVAL '1 day 12 hours', NOW() - INTERVAL '1 day 12 hours'),
(24, '변건우', 'Flask개발자', 'Crossplane 멀티클라우드 관리 #Crossplane #멀티클라우드', 'K8s로 클라우드 리소스를 관리하는 방법입니다. #Crossplane #멀티클라우드 #IaC', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '1 day 8 hours', NOW() - INTERVAL '1 day 8 hours'),
(25, '석예원', 'Go언어러버', 'Cert-Manager TLS 자동화 #TLS #보안', 'Let''s Encrypt 인증서를 자동 갱신하는 방법입니다. #TLS #보안 #K8s', 'PUBLIC', 356, 62, 0, false, false, false, NOW() - INTERVAL '1 day 4 hours', NOW() - INTERVAL '1 day 4 hours'),
(26, '길민준', 'Rust전도사', 'External Secrets Operator #시크릿 #보안', '외부 시크릿 저장소와 K8s를 연동하는 방법입니다. #시크릿 #보안 #K8s', 'PUBLIC', 298, 53, 0, false, false, false, NOW() - INTERVAL '1 day', NOW() - INTERVAL '1 day'),
(27, '노서아', 'C++마스터', 'Vault 시크릿 관리 #Vault #보안', 'HashiCorp Vault로 시크릿을 안전하게 관리하는 방법입니다. #Vault #보안 #시크릿', 'PUBLIC', 423, 74, 0, false, false, false, NOW() - INTERVAL '20 hours', NOW() - INTERVAL '20 hours'),
(28, '도연우', 'Kotlin개발자', 'OPA Gatekeeper 정책 관리 #OPA #정책', 'K8s 클러스터 정책을 코드로 관리하는 방법입니다. #OPA #정책 #K8s', 'PUBLIC', 278, 49, 0, false, false, false, NOW() - INTERVAL '16 hours', NOW() - INTERVAL '16 hours'),
(29, '하시우', 'Swift전문가', 'Falco 런타임 보안 #Falco #보안', 'K8s 런타임 보안 모니터링 도구 Falco 활용법입니다. #Falco #보안 #K8s', 'PUBLIC', 312, 55, 0, false, false, false, NOW() - INTERVAL '12 hours', NOW() - INTERVAL '12 hours'),
(30, '목지안', 'TypeScript러버', 'Trivy 취약점 스캔 #Trivy #보안', '컨테이너 이미지 취약점을 스캔하는 방법입니다. #Trivy #보안 #컨테이너', 'PUBLIC', 289, 51, 0, false, false, false, NOW() - INTERVAL '8 hours', NOW() - INTERVAL '8 hours'),

-- 개발자 라이프/커리어 (81-100)
(31, '유다온', 'GraphQL전문가', '시니어 개발자로 성장하기 #커리어 #성장', '주니어에서 시니어로 성장하며 배운 점들입니다. #커리어 #성장 #개발자', 'PUBLIC', 678, 116, 0, false, false, false, NOW() - INTERVAL '7 hours', NOW() - INTERVAL '7 hours'),
(32, '차하준', 'REST API마스터', '개발자 이직 협상 전략 #이직 #연봉', '이직 시 연봉 협상에서 배운 노하우입니다. #이직 #연봉 #협상', 'PUBLIC', 789, 135, 0, false, false, false, NOW() - INTERVAL '6 hours', NOW() - INTERVAL '6 hours'),
(33, '추소율', 'MSA전문가', '기술 면접 준비 가이드 #면접 #취업', '기술 면접을 체계적으로 준비하는 방법입니다. #면접 #취업 #준비', 'PUBLIC', 567, 97, 0, false, false, false, NOW() - INTERVAL '5 hours', NOW() - INTERVAL '5 hours'),
(34, '피우진', 'Docker마스터', '원격 근무 생산성 팁 #원격근무 #생산성', '재택근무에서 생산성을 유지하는 나만의 루틴입니다. #원격근무 #생산성 #팁', 'PUBLIC', 456, 79, 0, false, false, false, NOW() - INTERVAL '4 hours 30 minutes', NOW() - INTERVAL '4 hours 30 minutes'),
(35, '함수빈', 'K8s전문가', '개발자 번아웃 예방법 #번아웃 #멘탈', '번아웃을 미리 예방하고 관리하는 방법입니다. #번아웃 #멘탈 #건강', 'PUBLIC', 623, 107, 0, false, false, false, NOW() - INTERVAL '4 hours', NOW() - INTERVAL '4 hours'),
(36, '곽하율', 'AWS전문가', '사이드 프로젝트로 수익 만들기 #사이드프로젝트 #수익', '사이드 프로젝트를 수익화한 경험을 공유합니다. #사이드프로젝트 #수익 #창업', 'PUBLIC', 734, 126, 0, false, false, false, NOW() - INTERVAL '3 hours 30 minutes', NOW() - INTERVAL '3 hours 30 minutes'),
(37, '성시온', 'Azure마스터', '오픈소스 메인테이너 되기 #오픈소스 #기여', '오픈소스 프로젝트 메인테이너가 된 경험입니다. #오픈소스 #기여 #커뮤니티', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '3 hours', NOW() - INTERVAL '3 hours'),
(38, '양윤서', 'GCP전문가', '개발 블로그 성장 전략 #블로그 #브랜딩', '기술 블로그 방문자를 늘린 전략을 공유합니다. #블로그 #브랜딩 #마케팅', 'PUBLIC', 512, 88, 0, false, false, false, NOW() - INTERVAL '2 hours 30 minutes', NOW() - INTERVAL '2 hours 30 minutes'),
(39, '민재원', 'CI/CD마스터', '개발자 유튜브 시작하기 #유튜브 #콘텐츠', '개발 유튜브 채널을 시작하며 배운 점들입니다. #유튜브 #콘텐츠 #크리에이터', 'PUBLIC', 478, 82, 0, false, false, false, NOW() - INTERVAL '2 hours', NOW() - INTERVAL '2 hours'),
(40, '복하윤', 'Git전문가', '기술 서적 집필 경험담 #집필 #책', '기술 서적을 집필하며 겪은 과정을 공유합니다. #집필 #책 #경험', 'PUBLIC', 389, 67, 0, false, false, false, NOW() - INTERVAL '1 hour 30 minutes', NOW() - INTERVAL '1 hour 30 minutes'),
(41, '설지호', '코드리뷰어', '개발자 커뮤니티 운영기 #커뮤니티 #운영', '개발자 커뮤니티를 운영하며 배운 점들입니다. #커뮤니티 #운영 #네트워킹', 'PUBLIC', 356, 62, 0, false, false, false, NOW() - INTERVAL '1 hour', NOW() - INTERVAL '1 hour'),
(42, '옥서준', '테스트마스터', '컨퍼런스 발표자 되기 #컨퍼런스 #발표', '기술 컨퍼런스에서 발표하기까지의 과정입니다. #컨퍼런스 #발표 #성장', 'PUBLIC', 423, 73, 0, false, false, false, NOW() - INTERVAL '50 minutes', NOW() - INTERVAL '50 minutes'),
(43, '엄다은', 'QA전문가', '스타트업 vs 대기업 개발자 #스타트업 #대기업', '양쪽에서 일해본 경험을 비교합니다. #스타트업 #대기업 #비교', 'PUBLIC', 567, 97, 0, false, false, false, NOW() - INTERVAL '40 minutes', NOW() - INTERVAL '40 minutes'),
(44, '예민성', 'PM지망생', '개발자 연봉 협상 실전 #연봉 #협상', '연봉 협상에서 실제로 활용한 전략입니다. #연봉 #협상 #실전', 'PUBLIC', 689, 118, 0, false, false, false, NOW() - INTERVAL '30 minutes', NOW() - INTERVAL '30 minutes'),
(45, '남궁준', 'UX디자이너', '프리랜서 개발자 가이드 #프리랜서 #독립', '프리랜서로 독립하기 위한 준비 가이드입니다. #프리랜서 #독립 #커리어', 'PUBLIC', 534, 92, 0, false, false, false, NOW() - INTERVAL '25 minutes', NOW() - INTERVAL '25 minutes'),
(46, '선우아', 'UI디자이너', '해외 취업 준비 과정 #해외취업 #글로벌', '미국 테크 기업 취업 준비 과정을 공유합니다. #해외취업 #글로벌 #미국', 'PUBLIC', 612, 105, 0, false, false, false, NOW() - INTERVAL '20 minutes', NOW() - INTERVAL '20 minutes'),
(47, '황보율', '기획자', '개발자 건강 관리 가이드 #건강 #운동', '앉아서 일하는 개발자를 위한 건강 관리법입니다. #건강 #운동 #자세', 'PUBLIC', 445, 77, 0, false, false, false, NOW() - INTERVAL '15 minutes', NOW() - INTERVAL '15 minutes'),
(48, '독고서', '마케터', '효율적인 학습 방법론 #학습 #공부', '새로운 기술을 빠르게 습득하는 방법입니다. #학습 #공부 #방법론', 'PUBLIC', 489, 84, 0, false, false, false, NOW() - INTERVAL '10 minutes', NOW() - INTERVAL '10 minutes'),
(49, '사공윤', 'SEO전문가', '개발자 멘토링 시작하기 #멘토링 #성장', '주니어 개발자를 멘토링하며 배운 점들입니다. #멘토링 #성장 #리더십', 'PUBLIC', 378, 65, 0, false, false, false, NOW() - INTERVAL '5 minutes', NOW() - INTERVAL '5 minutes'),
(50, '제갈호', '데이터사이언티스트', '2026년 개발자 전망 #트렌드 #전망', '2026년 개발자 시장과 기술 트렌드를 전망합니다. #트렌드 #전망 #2026', 'PUBLIC', 723, 124, 0, false, false, false, NOW(), NOW());
